vim.opt.autoindent = true
vim.opt.background = "dark"
vim.opt.backup = false
vim.opt.belloff = "all"
vim.opt.breakindent = true
vim.opt.cmdheight = 1
vim.opt.colorcolumn = "81"
vim.opt.compatible = false
vim.opt.cursorline = true
vim.opt.encoding = "utf-8"
vim.opt.errorbells = false
vim.opt.expandtab = true
vim.opt.fileformat = "unix"
vim.opt.hidden = true
vim.opt.history = 1000
vim.opt.hlsearch = false
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.isfname:append("@-@")
vim.opt.laststatus = 2
-- vim.opt.linebreak = true
vim.opt.mouse = 'a'
vim.opt.number = true
vim.opt.path:append("**")
vim.opt.relativenumber = true
vim.opt.scrolloff = 10
vim.opt.shiftwidth = 2
vim.opt.showcmd = true
vim.opt.showmatch = true
vim.opt.showmode = true
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.softtabstop = 2
vim.opt.swapfile = false
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.textwidth = 80
vim.opt.timeoutlen = 250
vim.opt.undofile = true
vim.opt.updatetime = 50
vim.opt.wildignore = "*.docx, *.jpg, *.png, *.gif, *.pdf, *.pyc, *.exe, *.flv, *.img, *.xlsx"
vim.opt.wildmenu = true
vim.opt.wildmode = "longest:list:full"
vim.opt.wrap = true
vim.opt.writebackup = false 
