# re-bind send-prefix from <c-b> to <c-a>
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# reload config
bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded"

# use vim motions for pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# enable mouse support for swtiching panes/windows
set -g mouse-utf8 on
set -g mouse on
